This is makeindex, version 2.15 [TeX Live 2017] (kpathsea + Thai support).
Scanning style file ./report.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file report.acn....done (34 entries accepted, 0 rejected).
Sorting entries....done (185 comparisons).
Generating output file report.acr....done (42 lines written, 0 warnings).
Output written in report.acr.
Transcript written in report.alg.
